name: geolocation-author-automations-checks
on:
  push:
    branches:
      - develop
      - main
      - "release-*"
      - "hotfix-*"
      - "feature-*"
      - "feature_*"
      - "feature*"
  merge_group:
    types: [checks_requested]
    branches:
      - develop
      - main
      - "release-*"
      - "hotfix-*"
      - "feature-*"
      - "feature_*"
      - "feature*"
jobs:
  general-tests:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: |
          poetry lock --no-update
          poetry install --no-interaction
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run tests
        run: |
          source .venv/bin/activate
          coverage run -m pytest .
          coverage report
      #----------------------------------------------
      #          install and run linters
      #----------------------------------------------
      - name: Linting install
        run: python -m pip install black flake8 isort
      - name: Linting check
        run: |
          flake8 . --ignore=W191,E24,W504,E501,E262,E722,E251,W291,W293,E261,E305,E203,E226,E303,E225,E265,E222,F401,E302,E231,E111,E302,E265,E301,W292
          isort .
